word = input("Type the word here : ")
word = set(word)
print(word)
word2 = input("Type another word here : ")
union = word.union(set(word2))
print(union)
print("chars which are not in word2 are : ",union.difference(set(word2)))
print("chars which are in word2 are : ",union.intersection(set(word2)))
print("Sorting set : ", sorted(union))
